export const RouterPath = {
  root: '/',
  home: '/',
  login: '/login',
  signup: '/signup',
  signupUser: '/signup/user',
  signupTrainer: '/signup/trainer',
  mypage: '/mypage',
  registerBodyInfo: '/registerBodyInfo',
  registerCareer: '/registerCareer',
  preference: '/preference',
  clientFinder: '/clientFinder',
  proposal: '/proposal/:userId',
  sentProposal: '/sentProposal',
  receivedProposal: '/receivedProposal',
  trainerDetail: '/trainerDetail/:trainerId',
  userPtSchedule: '/userPtSchedule',
  trainerPtSchedule: '/trainerPtSchedule/:ptId',
};
